name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: cloudflare/wrangler-action@v3

      - name: Deploy to Cloudflare Pages
        run: |
          CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
          wrangler pages deploy angular-ssr/dist/cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
